CREATE DATABASE HMS;
USE HMS;
CREATE TABLE PERSON(ID int PRIMARY KEY, FIRSTNAME  varchar (25), MIDDLENAME varchar (30), 
SURNAME varchar (40), EMAIL varchar(35), CONTACTNUMBER bigint, DATE_RELATED_TO_BIRTH_DATE date,
GENDER varchar (27), EMERGENCY_CONTACT_NUMBER bigint, ADDRESSID INT);
CREATE TABLE ADDRESS( ID int primary KEY, COUNTRY varchar(30),STATE VARCHAR(40), CITY VARCHAR(36) , STREET VARCHAR(30) , HOUSE_NUMBER VARCHAR(40));
CREATE table STAFFTYPE(ID int PRIMARY KEY, TYPE varchar (37));
CREATE TABLE STAFFGRADE (ID INT PRIMARY KEY, GRADE varchar (40));
CREATE TABLE STAFFCATEGORY (ID INT PRIMARY KEY);
CREATE TABLE STAFF (ID INT PRIMARY KEY, STAFFCATEGORYID INT ,STAFFTYPEID int,STAFFGRADEDID int,PERSONID int);
drop TABLE STAFF;
CREATE TABLE ERSTAFF (
    ID INT PRIMARY KEY,
    name VARCHAR(39),
    starttime TIME,
    endtime TIME,
    INCHARGESTAFFID INT
);


 

 